name: Fifteenth Workflow
on: push
run-name: Artifact testing

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Math expression  # создается мат. выражение и результат записывается в файл
        run: |
          expr 2 + 2 > math-result.txt
          ls -la
      - name: Upload result file  # использование экшена загрузки артефакта
        uses: actions/upload-artifact@v4
        with:
          name: math-result  # ключ для названия файла 
          path: math-result.txt # путь к файлу

  another-job:  # джоб для внесения изменений в артефакт
    runs-on: ubuntu-latest
    needs: first-job  # запуск после джоба создания
    steps:
      - name: Download file  # загрузка файла артефакта
        uses: actions/download-artifact@v4
        with:
          name: math-result  # ключ по которому будет доставать артефакт
      - name: Edit artifact
        run: |
          value=`math-result.txt`
          expr value \* 2 > math-result.txt
      - name: Upload result file  # использование экшена загрузки артефакта
        uses: actions/upload-artifact@v4
        with:
          name: math-result  # ключ для названия файла 
          path: math-result.txt # путь к файлу
 
  second-job:
    runs-on: ubuntu-latest
    needs: first-job  # джобы должны запускатсья последовательно а не параллельно как по умолчанию
    steps:
      - name: Download file  # загрузка файла артефакта
        uses: actions/download-artifact@v4
        with:
          name: math-result  # ключ по которому будет доставать артефакт
      - name: Display files data
        run: |
          cat math-result.txt
