name: Sixteenth_workflow
on: push
run-name: Matrix

jobs:
  testing-matrix:
    strategy:
      matrix:
        digs: [12, 14, 18]
 
    runs-on: ubuntu-latest
    steps:
      - name: display-dig
        run: |
          echo ${{ matrix.digs }}


   # runs-on: ubuntu-latest
  #  steps:
  #    - run: node -v
   #   - uses: actions/setup-node@v3
   #     with:
    #      node-version: ${{ matrix.node-version }}
   #   - run: node -v