name: Seventeenth Workflow
on: 
  workflow_dispatch:
    inputs:
      title:
        description: "Custom Title"
        type: string
        default: "Testing text title"
        required: false  # не обязательный

jobs:
  call-workflow:
    uses: ./.github/workflows/workflow.yml
    with:
      title: ${{ inputs.title }}
  call-external-workflow:
    uses: MkTGts/workflows/.github/workflows/workflow.yml@main
    secrets:
      PASSWORD: ${{ secrets.PASSWORD }}
  displat-output:
    runs-on: ubuntu-latest
    needs: call-workflow
    steps:
      - run: echo ${{ needs.call-workflow.outputs.date }}
