name: Concurrency
on: workflow_dispatch
run-name: Testing Concurrency
concurrency: concurrency-testing
jobs: 
  test-concurrency:
    runs-on: ubuntu-latest
    steps:
      - name: Some Step
        run: sleep 50
        timeout-minutes: 1
