# запускает workflow по заданному кастомному types
name: Nineth workflow
on: 
  repository_dispatch:
    types: [test_type]  # types вот здесь задаются



jobs:
  run-nineth-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run:
          echo "Title ${{ github.event.client_payload.titleTest }}"
          echo "Title ${{ github.event.client_payload.secondTester }}"